spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:80
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<path>.*),/api/vendor/$\{path}
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - id: product-service
          uri: https://localhost:80
          predicates:
            - Path=/products
          filters:
            - RewritePath=/users/(?<path>.*),/api/$\{path}
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:8081'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods: '*'
logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG