server:
  port: 80

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<path>.*),/api/vendor/$\{path}
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - id: product-service
          uri: http://product
          predicates:
            - Path=/products/**
          filters:
            - RewritePath=/users/(?<path>.*),/api/$\{path}
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://pmw.joybox.info'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods: '*'

management:
  endpoints:
    web:
      base-path: /
